### Import Libraries

In [43]:
import pandas as pd
import seaborn as sns
import numpy as np
import plotly.plotly as py
import matplotlib.pyplot as plt

from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

import plotly.graph_objs as go
import warnings
warnings.filterwarnings('ignore')
import os

### List of data set

In [10]:
print(os.listdir('dataset'))

['2015.csv', '2016.csv', '2017.csv']

### Set up data set

In [11]:
# Load dataset
data2015 = pd.read_csv('./dataset/2015.csv')
data2016 = pd.read_csv('./dataset/2016.csv')
data2017 = pd.read_csv('./dataset/2017.csv')

In [44]:
#World Happiness - Data Head 2015
data2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [22]:
#World Happiness - Data Tail 2015
data2015.tail()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [23]:
#World Happiness - Data Head 2016
data2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [24]:
#World Happiness - Data Tail 2016
data2016.tail()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [25]:
#World Happiness - Data Head 2017
data2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [28]:
#World Happiness - Data Tail 2017
data2017.tail()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [29]:
data2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
Country                          158 non-null object
Region                           158 non-null object
Happiness Rank                   158 non-null int64
Happiness Score                  158 non-null float64
Standard Error                   158 non-null float64
Economy (GDP per Capita)         158 non-null float64
Family                           158 non-null float64
Health (Life Expectancy)         158 non-null float64
Freedom                          158 non-null float64
Trust (Government Corruption)    158 non-null float64
Generosity                       158 non-null float64
Dystopia Residual                158 non-null float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [30]:
data2017.describe()

,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
count,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000,155.000000
mean,78.000000,5.354019,5.452326,5.255713,0.984718,1.188898,0.551341,0.408786,0.246883,0.123120,1.850238
std,44.888751,1.131230,1.118542,1.145030,0.420793,0.287263,0.237073,0.149997,0.134780,0.101661,0.500028
min,1.000000,2.693000,2.864884,2.521116,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.377914
25%,39.500000,4.505500,4.608172,4.374955,0.663371,1.042635,0.369866,0.303677,0.154106,0.057271,1.591291
50%,78.000000,5.279000,5.370032,5.193152,1.064578,1.253918,0.606042,0.437454,0.231538,0.089848,1.832910
75%,116.500000,6.101500,6.194600,6.006527,1.318027,1.414316,0.723008,0.516561,0.323762,0.153296,2.144654
max,155.000000,7.537000,7.622030,7.479556,1.870766,1.610574,0.949492,0.658249,0.838075,0.464308,3.117485

In [31]:
#Country Counts Unique
countries = data2017.Country.unique()
for country in countries:
    print(country)

Norway
Denmark
Iceland
Switzerland
Finland
Netherlands
Canada
New Zealand
Sweden
Australia
Israel
Costa Rica
Austria
United States
Ireland
Germany
Belgium
Luxembourg
United Kingdom
Chile
United Arab Emirates
Brazil
Czech Republic
Argentina
Mexico
Singapore
Malta
Uruguay
Guatemala
Panama
France
Thailand
Taiwan Province of China
Spain
Qatar
Colombia
Saudi Arabia
Trinidad and Tobago
Kuwait
Slovakia
Bahrain
Malaysia
Nicaragua
Ecuador
El Salvador
Poland
Uzbekistan
Italy
Russia
Belize
Japan
Lithuania
Algeria
Latvia
South Korea
Moldova
Romania
Bolivia
Turkmenistan
Kazakhstan
North Cyprus
Slovenia
Peru
Mauritius
Cyprus
Estonia
Belarus
Libya
Turkey
Paraguay
Hong Kong S.A.R., China
Philippines
Serbia
Jordan
Hungary
Jamaica
Croatia
Kosovo
China
Pakistan
Indonesia
Venezuela
Montenegro
Morocco
Azerbaijan
Dominican Republic
Greece
Lebanon
Portugal
Bosnia and Herzegovina
Honduras
Macedonia
Somalia
Vietnam
Nigeria
Tajikistan
Bhutan
Kyrgyzstan
Nepal
Mongolia
South Africa
Tunisia
Palestinian Territories
Egypt
Bulgaria
Sierra Leone
Cameroon
Iran
Albania
Bangladesh
Namibia
Kenya
Mozambique
Myanmar
Senegal
Zambia
Iraq
Gabon
Ethiopia
Sri Lanka
Armenia
India
Mauritania
Congo (Brazzaville)
Georgia
Congo (Kinshasa)
Mali
Ivory Coast
Cambodia
Sudan
Ghana
Ukraine
Uganda
Burkina Faso
Niger
Malawi
Chad
Zimbabwe
Lesotho
Angola
Afghanistan
Botswana
Benin
Madagascar
Haiti
Yemen
South Sudan
Liberia
Guinea
Togo
Rwanda
Syria
Tanzania
Burundi
Central African Republic

In [40]:
#Country Counts
print(data2017['Country'].value_counts())

Haiti                       1
Libya                       1
Dominican Republic          1
Central African Republic    1
Pakistan                    1
Syria                       1
Argentina                   1
Bosnia and Herzegovina      1
Taiwan Province of China    1
Singapore                   1
Rwanda                      1
Cyprus                      1
Namibia                     1
Nigeria                     1
Lithuania                   1
Netherlands                 1
Botswana                    1
Russia                      1
Armenia                     1
Jordan                      1
Morocco                     1
Guinea                      1
Lesotho                     1
Peru                        1
Ecuador                     1
Uganda                      1
Albania                     1
Belarus                     1
Venezuela                   1
Burundi                     1
                           ..
Afghanistan                 1
Slovenia                    1
Georgia                     1
Costa Rica                  1
Belgium                     1
Slovakia                    1
Uruguay                     1
Mozambique                  1
United States               1
China                       1
Turkmenistan                1
Bahrain                     1
Bulgaria                    1
New Zealand                 1
Cameroon                    1
Nepal                       1
Mongolia                    1
Canada                      1
Vietnam                     1
Myanmar                     1
Yemen                       1
Ireland                     1
Togo                        1
Nicaragua                   1
Mexico                      1
Liberia                     1
Congo (Brazzaville)         1
Finland                     1
Angola                      1
Sri Lanka                   1
Name: Country, Length: 155, dtype: int64

In [41]:
#Regions unique
regions=data.Region.unique()
for reg in regions:
    print(reg)

Western Europe
North America
Australia and New Zealand
Middle East and Northern Africa
Latin America and Caribbean
Southeastern Asia
Central and Eastern Europe
Eastern Asia
Sub-Saharan Africa
Southern Asia

In [42]:
#Regions Counts
print(data['Region'].value_counts())

Sub-Saharan Africa                 40
Central and Eastern Europe         29
Latin America and Caribbean        22
Western Europe                     21
Middle East and Northern Africa    20
Southeastern Asia                   9
Southern Asia                       7
Eastern Asia                        6
North America                       2
Australia and New Zealand           2
Name: Region, dtype: int64